<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-11-09T10:05:06Z" name="Default suite" finished-at="2020-11-09T10:05:06Z" duration-ms="24">
    <groups>
    </groups>
    <test started-at="2020-11-09T10:05:06Z" name="Default test" finished-at="2020-11-09T10:05:06Z" duration-ms="24">
      <class name="com.selenium.practise.Dataprovider">
        <test-method signature="data(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.selenium.practise.Dataprovider@5e2c3d18]" started-at="2020-11-09T15:35:06Z" name="data" data-provider="dataprovider" finished-at="2020-11-09T15:35:06Z" duration-ms="8" status="FAIL">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
The data provider is trying to pass 2 parameters but the method com.selenium.practise.Dataprovider#data takes 3 and TestNG is unable in inject a suitable object]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
The data provider is trying to pass 2 parameters but the method com.selenium.practise.Dataprovider#data takes 3 and TestNG is unable in inject a suitable object
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1367)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1365)
	... 17 more
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- data -->
      </class> <!-- com.selenium.practise.Dataprovider -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
